version: "3.5"

volumes:
  pkg:

services:

  app:
    image: twilio:dev
    volumes:
    - pkg:/go/pkg
    - ./:/go/src/github.com/68696c6c/twilio
    working_dir: /go/src/github.com/68696c6c/twilio
    env_file:
    - .secret.env
